configurations:
- index: 0
  name: "Age"
  type: "INTEGER"
  scale: "RATIO"
  configurations: []
- index: 1
  name: "Sex"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 2
  name: "ChestPainType"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 3
  name: "RestingBP"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 4
  name: "Cholesterol"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 5
  name: "FastingBS"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 6
  name: "RestingECG"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 7
  name: "MaxHR"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
- index: 8
  name: "ExerciseAngina"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 9
  name: "Oldpeak"
  type: "DECIMAL"
  scale: "RATIO"
  configurations: []
- index: 10
  name: "ST_Slope"
  type: "STRING"
  scale: "NOMINAL"
  configurations: []
- index: 11
  name: "HeartDisease"
  type: "INTEGER"
  scale: "INTERVAL"
  configurations: []
anonymization:
  privacyModels:
    - name: anonymization_tabular
      type: tabular
      modelConfiguration:
        riskThresholdType: Max
        riskThresholdValue: 0.5
        generalizationSetting: Global
        suppressionLimit: 0.8
  attributeConfiguration:
    - attributeProtection: MICRO_AGGREGATION
      dataType: INTEGER
      index: 0
      intervalSize: 10
      name: Age
      scale: RATIO
    - attributeProtection: RECORD_DELETION
      dataType: STRING
      index: 1
      intervalSize: null
      name: Sex
      scale: NOMINAL
synthetization_configuration:
  algorithm:
    synthesizer: arf
    type: cross-sectional
    version: "0.1"
    model_parameter:
      num_trees: 80
      min_node_size: 12
    model_fitting:
      max_iters: 10
    sampling:
      num_samples: 918
evaluation_configuration:
  data_format: cross-sectional
  resemblance:
    mean: {}
    standard_deviation: {}
    variance: {}
    distinct_values: {}
    mode: {}
    fifth_percentile: {}
    median: {}
    q1: {}
    q3: {}
    ninety_fifth_percentile: {}
    minimum: {}
    maximum: {}
    density: {}
    histogram: {}
    kolmogorov_smirnov: {}
    hellinger_distance: {}
    frequency_plot: {}
    calculate_columnwise_correlations: {}
    calculate_columnwise_correlations_distance: {}
    missing_values_count: {}
    visualize_columnwise_correlations: {}
  utility:
    machine_learning:
      train_size: 0.8
      target_variable: HeartDisease
    discriminator_based_evaluation:
      train_size: 0.8
risk_assessment_configuration:
  singlingout_uni:
    n_attacks: 100
  attribute_inference:
    n_attacks: 100
  linkage:
    n_attacks: 100
    available_columns:
      - ChestPainType
      - RestingBP
      - Cholesterol
      - FastingBS
      - RestingECG
      - MaxHR
      - ExerciseAngina
      - Oldpeak
      - ST_Slope
    unavailable_columns:
      - Age
      - Sex
      - HeartDisease
  data_format: cross-sectional
  train_fraction: 0.8
  targets: []
  n_random_targets: 5
  n_outlier_targets: 5
  n_iterations: 1
  columns_excluded: []
  singlingout_multi:
    n_attacks: 100
  metrics:
    uniqueness: true
